name: CivEvents
version: '1.0.0'
main: nos.civevents.CivEvents
api-version: '1.20'
authors: [Nosidian]
description: A Plugin Created By Nosidian
softdepend: [LuckPerms, ProtocolLib]

commands:
  civadmins:
    permission: civevents.admin
    permission-message: Permission = civevents.admin
    aliases: [ca, civa, cadmin]
  gms:
    permission: civevents.survival
    permission-message: Permission = civevents.survival
  gmc:
    permission: civevents.creative
    permission-message: Permission = civevents.creative
  gma:
    permission: civevents.adventure
    permission-message: Permission = civevents.adventure
  gmsp:
    permission: civevents.spectator
    permission-message: Permission = civevents.spectator
  civban:
    permission: civevents.ban
    permission-message: Permission = civevents.ban
    aliases: [cb, civb, cban]
  antiscythers:
    permission: civevents.scythers
    permission-message: Permission = civevents.scythers
    aliases: [as, scyther, scythers]
  civcivilizations:
    permission: civevents.civilizations
    permission-message: Permission = civevents.civilizations
    aliases: [cc, civc, civcivilization]
  civdeaths:
    permission: civevents.death
    permission-message: Permission = civevents.death
    aliases: [cd, civd, civdeath]
  civentities:
    permission: civevents.entity
    permission-message: Permission = civevents.entity
    aliases: [ce, cive, civentity]
  civflags:
    permission: civevents.flag
    permission-message: Permission = civevents.flag
    aliases: [cf, civf, civflag]
  civhungergames:
    permission: civevents.location
    permission-message: Permission = civevents.location
    aliases: [hg, hungergame, hungergames]
  civitems:
    permission: civevents.item
    permission-message: Permission = civevents.item
    aliases: [ci, civi, civitem]
  civloot:
    permission: civevents.loot
    permission-message: Permission = civevents.loot
    aliases: [cl, cloot]
  civportals:
    permission: civevents.portal
    permission-message: Permission = civevents.portal
    aliases: [cportal, civportal, portal]
  civpackages:
    permission: civevents.package
    permission-message: Permission = civevents.package
    aliases: [cp, civp, civpackage]
  civrecipes:
    permission: civevents.recipeall
    permission-message: Permission = civevents.recipeall
    aliases: [cr, civr, civrecipe]
  recipes:
    permission: civevents.recipe
    permission-message: Permission = civevents.recipe
    aliases: [recipe, craft, crafts]
  team:
    permission: civevents.team
    permission-message: Permission = civevents.team
    aliases: [t, teams, ct, civt, civteam, civteams]
  civworlds:
    permission: civevents.world
    permission-message: Permission = civevents.world
    aliases: [cw, civw, civworld]
  godmode:
    permission: civevents.godmode
    permission-message: Permission = civevents.godmode
    aliases: [gm]